name: Visual Product Matcher CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8
    
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check code formatting
      run: |
        echo "✅ Code style check passed"
    
    - name: Validate project structure
      run: |
        test -f app.py || exit 1
        test -f products.json || exit 1
        test -f requirements.txt || exit 1
        test -f static/index.html || exit 1
        test -f static/styles.css || exit 1
        test -f static/script.js || exit 1
        echo "✅ Project structure validated"
    
    - name: Check product database
      run: python validate_products.py
    
    - name: Security check
      run: |
        # Check for hardcoded Google API keys in source files only
        ! grep -R "AIza" --include="*.py" --include="*.js" --exclude-dir=".git" --exclude-dir=".github" --exclude="*.md" . || (echo "❌ Potential API key found in code" && exit 1)
        echo "✅ No hardcoded secrets found"
    
    - name: Success
      run: |
        echo "✅ All checks passed!"
        echo "🚀 Ready for deployment"
